language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: utf-8
  bucket: static-react-spike-dev
  region: eu-west-2
  acl: public_read
env:
  global:
  - secure: fExcLDSvB9E4YUalhXeiBDFsM8aEkV2ahMLwk6722l5SiLdMk6+wMo7vSgPlsMq/XmjMCYqYt0itQqOOxATLxjNWSGCkw30wDRdt67h0TYA/1j5Bqb63zyYedPCj5AZp+xQTicwdTP8Lxn8Ny1NtUU8/RNWiT8ZTOU8ZDqe4HDfGVp/a0/QtXdeYpng3aOgJSyYnJ8ki3XhnPXm03jih5DvNBGjzhRrucFREDDlj+Qaw8rdWzp7xpIh9kzz38n2eWXt66RLvu5oIzNksm3w7du8DL2UTPDiUwiRK1KkG42cQLBcR6AXue/5sVYfw/S0clvMQ/pk72doaNYZZNkPHnkTez/XPP95bu8b3MQfr+4TGKOc6febH5D1ARGdgz37X65bJRnoOcM3WNcfUYbrgfqEPEdiJeHsaW5gXpG50447JYzHFeeIvbuO5PKUfirv/7YtRpAVlpZdOV4m82uhr0oNRhIv+VONnV40SU4nnOtE29OQ0+6srd6ayQ//yLdUXPFzbIzZv8KUHeF92N6dZyCsS806DAt6eY7YG9xzAp8KcovgihfqNtIoj9vcn5fcs3GMf8LKQH/ZQcnCEZmNJil6q2EzYrG0+a/Nnxnhsd6d5UuZgB1w6YyGayjxThtfDgfoOJWZ1rzRYDlAVGjFwy+H4afcveQdJgldM7bAE9YU=
  - secure: dPyvEXKkjBN+0mDIcXQtQBNRUwHpVr+EHaVhi2Sak6XTjls7vOfK1ALXTveix2twDMbAxYlKo71A6nmbHqBodAbwuphhLpJc3wzhL6FzAIXSEtqLbZOAuSv5u+BEXJrSOQzgVgOYfAzkdYy1svQbGulKErL7rlVdTo6OJ+gw+m7XA5obnubWv9QUZ1NmHQ5GhGoiq2gURHpB6/ixHY04+1aDpSls060Jj483Oc2isVlEsex3jAZoTeNwc0woktP6foengkGpzKVsj89aceMxUPD4ssQeHcIzhvrM0VFAOfJawdRC6dYX1RXh4qoUbG1LcVTts+d92yJ4dZNS1f72YB48V5YDhmbMFn6ez+QtmmZHRXxJsukT6AdPfbLvwG6r316KsBtH+x8sNYgXFz17YiXnFSPGvzMAGzHJce0n2CslVAC1Jj11ZFPlOXrCAYbuhR7DKEYEs03i+r6uEoM+xYm61+IQzGT5HORNenkeEO8K2xtBPRIW3bQs+wVcyMJUfhBhRVRVP9CGxqED0124kDQQWJx+p4EnLd5aGtaWuYffiuzN6mRyAA5HlLuWJsNOegDH/urpCG/e60QxLjqDz51E0lNRRdVyDdA4DsvbP4i6K9ubwFPyNiCxLm9hYzWwO9XpISj2+PyuKR8Q45fmTRGdgA5WbOBRac6QbcrOWuM=
  - secure: qroPpTcSBGVl8dYeG5FklfXnKofVxE1CBxvnywlz2cpj+bC29uJtgmlzVjsY74Oor7Q45DuAr/8Av3Vs9VrcWVz8z8smPFIPS0WOEoZ7Drv+DDu3rMTJzajYRNzComL3uxkmOx+sVjnucOabbFF+/FenGN/Ub97/hXu7QgXw/kzv2SHGHmATONY0lz8uaAbRZEI3ClkomHKR5isoFWiPo22U7v1VOM8WK90YbSo3TcEKb6/VeEZi+zlCvP9krTxEc/ZfE4OSN/WHx9rkd6KoqsyYeB/8JG9GTB4AGiUd3Zf7qTZqgpxaWagF3srJXteqnVSrKo+uafmyeQiP9RoC5fTMLSJOKUfuZ0ciDSnqX11/RoVaNUMO6J9KVWu2zmwStVf1im3XRQAxLynifolc33YVJf/2dVEMrfgL1FwQ6CRQTZXgWzWuum/Uvil+63ejV5lWiT6qzyk2e5m99DhDCxX7lkQia0rlng/cfnKDATD7KmkYgKc3kMEJerhLiKBrs0vf2t9DxZR30rW+Vfx5bFBvA+RPulg/jLFJY/9G9DspX4zU1GpDinudJLCjkFfqRGqeVARxCLHetYp/kPP6I79QvpNHWD2KI63tFEVdfItQntGxcY4Ty/tdINM6JlzYnJ9G8arN4E/Vp8zVmzam/G/EKS1SUsnwSOqXQRw75a8=
